### ISSUE TITLE
[BUG] TypeError: i18next.init is not a function

### ISSUE THREAD

**Issue by ndelangen** [compodoc/compodoc#1643]
##### **Overview of the issue**

The ecosystem CI for storybook is catching some regression, I'm unsure if it's on compodoc's side or somewhere else.

5 hours ago a new asndbox was generated (it's automated every 24h):
https://github.com/storybookjs/sandboxes/commit/1cedd2d1f7e36fd8996cdf3ed3063eaf84aef600

This shows us the change: compodoc was upgraded to:
https://github.com/compodoc/compodoc/releases/tag/1.1.27

Then our ecosystem CI tries to bootstrap storybook on top of the sandbox, as well as generate a storybook static build.
This fails:
https://app.circleci.com/pipelines/github/storybookjs/storybook/103879/workflows/2a8f97f7-0fc3-49e6-9a8e-978d431bb698/jobs/889804/parallel-runs/16?filterBy=FAILED

The full error:
```
1.1.27

TypeScript version used by Compodoc : 5.8.3
TypeScript version of current project : 5.9.2
Node.js version : v22.15.0
Operating system : Linux 6.8

[07:28:42] No configuration file found, switching to CLI flags.
[07:28:42] Using provided source folder
[07:28:42] Using tsconfig file : /tmp/storybook/sandbox/angular-cli-default-ts/tsconfig.json
[07:28:42] Including      : /tmp/storybook/code/addons/vitest/template/stories/basics.stories.ts
[07:28:42] Including      : /tmp/storybook/code/addons/vitest/template/stories/unhandled-errors.stories.ts
[07:28:42] TypeError: i18next.init is not a function
[07:28:42] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
    at makeError (/tmp/storybook/scripts/node_modules/execa/lib/error.js:59:13)
    at handlePromise (/tmp/storybook/scripts/node_modules/execa/index.js:119:50)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async /tmp/storybook/scripts/combine-compodoc.ts:44:7
    at async Promise.all (index 5)
    at async run (/tmp/storybook/scripts/combine-compodoc.ts:40:21)
```

This is what line 40 of our `combine-compodoc.ts` looks like:
https://github.com/storybookjs/storybook/blob/b7c4b0bbaeffebfb07d3a8f47095d7303a1b1a10/scripts/combine-compodoc.ts#L45

##### **Operating System, Node.js, npm, compodoc version(s)**

`1.1.27`

```
TypeScript version used by Compodoc : 5.8.3
TypeScript version of current project : 5.9.2
Node.js version : v22.15.0
Operating system : Linux 6.8
```

##### **Angular configuration, a `package.json` file in the root folder**

https://github.com/storybookjs/sandboxes/blob/1cedd2d1f7e36fd8996cdf3ed3063eaf84aef600/angular-cli/default-ts/after-storybook/package.json

##### **Compodoc installed globally or locally ?**

Locally

##### **If possible sourcecode of the file where it breaks**

I don't have a lot to go on, but I did a search for `i18next.init` in our codebases, and wasn't able to find anything, but it does show up in yours:
https://github.com/search?q=repo%3Acompodoc%2Fcompodoc%20i18next.init&type=code

##### **If possible your terminal logs before the error**

Link to the CI workflow log:
https://app.circleci.com/pipelines/github/storybookjs/storybook/103879/workflows/2a8f97f7-0fc3-49e6-9a8e-978d431bb698/jobs/889804/parallel-runs/16?filterBy=FAILED

##### **Motivation for or Use Case**

This is blocking Storybook's ecosystem CI, blocking releases.

##### **Reproduce the error**

This is essentially what the ecosystem CI does:

- Download the `after-storybook` dir from the sandboxes repository.
- Install dependencies
- Run the build-storybook command

##### **Related issues**

I did search for the error message before opening this ticket, but neither `i18next.init` nor a substring yielded any open issues.

##### **Suggest a Fix**

Sorry, that's out of my depth.
I'd be happy to make tweaks to our ecosystem CI setup if that helps work out what the problem is.

**Comment by vogloblinsky** [comment]
Fixed by 1.1.28 just published right now

**Comment by ndelangen** [comment]
Thank you @vogloblinsky 

I appreciate that a lot! 🙏

**Comment by vogloblinsky** [comment]
Power of open-source 😉

**Comment by mrSingh007** [comment]
the issue is still there in version 1.2.28.
Just created new angular 20 project and added storybook (npm create storybook@latest). In installation it asked to add recommended compodoc, which i also installed. Now storybook not running and error is same like in this ticket. Please reopen the issue @vogloblinsky @ndelangen

**Comment by vogloblinsky** [comment]
> the issue is still there in version 1.2.28. Just created new angular 20 project and added storybook (npm create storybook@latest). In installation it asked to add recommended compodoc, which i also installed. Now storybook not running and error is same like in this ticket. Please reopen the issue [@vogloblinsky](https://github.com/vogloblinsky) [@ndelangen](https://github.com/ndelangen)

can i have all your commands and steps to reproduce it ?
thanks

[EDIT]
just tried :
- `ng new compodoc-debug-storybook-i18next -S`
- `cd compodoc-debug-storybook-i18next`
- `npm create storybook@latest`
- `npm i`
- `ng run compodoc-debug-storybook-i18next:storybook``

Got error missing module 'connect', and compodoc 1.1.19 added by sorybook and not 1.1.28
Upgraded to 1.1.28, still have module 'connect' error...

**Comment by smlimasu** [comment]
@vogloblinsky i have the same issue persisted in v1.1.28, thanks for the fast patch!
i think the problem is, somehow your fix with the const i18next = require('i18next').default; - which is solving the root cause when hotfixed locally in my nodemodules - did not get trough, somehow, in the released 1.1.28?

Edit: Ok I see you removed the .default in a second commit before the release again, but this was the solution for the bug ^^

in the 
node_modules/@compodoc/compodoc/src/app/engines/i18n.engine.ts and node_modules/@compodoc/compodoc/dist/index-cli-Db3Dfhs4.js

for me, it is still - var i18next = require('i18next'); 

when i set it to var i18next = require('i18next').default;  in the dist folder, everything works perfectly! 

yes, i deleted all node modules etc. and in node_modules compodocs package.json shows 1.1.28

**Comment by mrSingh007** [comment]
Here are steps for creating fresh project @vogloblinsky :

1. ng new my-workspace --no-create-application
2. cd my-workspace
3. ng generate library my-lib
4. npm create storybook@latest          //accept yes for compodoc
5. Now try to run storybook with `npm run storybook`


Here are added Versions by above:
Angular: ^20.2.0
compodoc: ^1.1.28
storybook/angular: ^9.1.4

node version: v24.7.0

**Comment by vogloblinsky** [comment]
> [@vogloblinsky](https://github.com/vogloblinsky) i have the same issue persisted in v1.1.28, thanks for the fast patch! i think the problem is, somehow your fix with the const i18next = require('i18next').default; - which is solving the root cause when hotfixed locally in my nodemodules - did not get trough, somehow, in the released 1.1.28?
> 
> Edit: Ok I see you removed the .default in a second commit before the release again, but this was the solution for the bug ^^
> 
> in the node_modules/@compodoc/compodoc/src/app/engines/i18n.engine.ts and node_modules/@compodoc/compodoc/dist/index-cli-Db3Dfhs4.js
> 
> for me, it is still - var i18next = require('i18next');
> 
> when i set it to var i18next = require('i18next').default; in the dist folder, everything works perfectly!
> 
> yes, i deleted all node modules etc. and in node_modules compodocs package.json shows 1.1.28

It should be fine again in 1.1.29
I don't know why the previous fix was working on my machine and CI in 1.1.28...

**Comment by vogloblinsky** [comment]
Explanation : https://github.com/i18next/i18next/issues/2348

**Comment by smlimasu** [comment]
> Explanation : https://github.com/i18next/i18next/issues/2348

@vogloblinsky omg sorry for the hassle that led to your patches, well, I guess this was a cursed timeline with the compodoc release and the i18next mishaps on their side 🫣 

I want to say a huge thank you for the quick reaction on your side and the patches and the effort 💐

**Comment by ndelangen** [comment]
I'm still running into this even when using the latest `1.1.29`:

```
1.1.29

TypeScript version used by Compodoc : 5.8.3

TypeScript version of current project : 5.9.2

Node.js version : v22.15.0

Operating system : Linux 6.8

[13:33:20] No configuration file found, switching to CLI flags.
[13:33:20] Using provided source folder
[13:33:20] Using tsconfig file : /tmp/storybook/sandbox/angular-cli-default-ts/tsconfig.json
[13:33:20] Including      : /tmp/storybook/code/frameworks/angular/template/stories_angular-cli-default-ts/signal/button.component.ts
[13:33:20] Including      : /tmp/storybook/code/frameworks/angular/template/stories_angular-cli-default-ts/signal/button.stories.ts
[13:33:20] TypeError: Cannot read properties of undefined (reading 'init')
[13:33:20] Sorry, but there was a problem during parsing or generation of the documentation. Please fill an issue on github. (https://github.com/compodoc/compodoc/issues/new)
```

See CI log here:
https://app.circleci.com/pipelines/github/storybookjs/storybook/103922/workflows/b6fef8d4-ad6f-44eb-9944-c78181b4d888/jobs/890368

**Comment by smlimasu** [comment]
It seems like the compodoc patches are a bit "out of sync". 

Lets break it down, based on what I can see in the app/src/i18nEngine.ts per patch: 

compodoc v.1.1.27 + i18next 25.5.1 -> Error, missing require.default, was only EMS/"require" (i18next breaking change). 
compodoc v.1.1.28 + i18next 25.5.1/25.5.2 (depends of timestampf of npm i today) -> Error, missing require.default für 25.5.1, but 25.5.2 throws when "require.default" (18next released patch version same time)
compodoc v.1.1.29 + i18next 25.5.2 (i18n patch was out) -> require should be without default, but the compodoc patch still included require.default, i think without default only pushed to develop(?) -> cannot read undefined. 

--> I think a final patch is needed without the "default" but that means that people need to clean their node_modules to get i18next 25.5.2, if not failure again. 

Alternative: Compodoc Version 1.1.27 (I think) and v 1.1.28 should work without errors for all people installing after lunch today because they will get i18next 25.5.2.  

Or am I wrong?

**Comment by vogloblinsky** [comment]
@smlimasu 1.1.30 released with i18next pin to 25.5.2
